### PR TITLE
Add about to grow account

### PR DESCRIPTION
**Pull request by sahand-zeynol**
add about field(string) to grow_account table with migration files and fixed it in the handler, repo and model

### CODE REVIEW

**Review by Kpoke — COMMENTED** [review]
@sahand-zeynol seems like you only made an update to the database migration and not to the code as well

**Comment by sahand-zeynol** [comment]
@Kpoke yes, you were right. my commits were corrupted, I fixed it.

**Comment by Kpoke** [comment]
@sahand-zeynol awesome, can you also update the test to include the about field?

**Comment by sahand-zeynol** [comment]
@Kpoke I added about field in tests

**Pull request merged**
